"""delete contracted_prep, subscription_type_Streaming_pred, subscription_type_TV_pred, subscription_type_TV_and_Streaming_pred

Revision ID: 567c8994411d
Revises: 83913e4bf945
Create Date: 2024-07-13 18:57:01.902501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '567c8994411d'
down_revision: Union[str, None] = '83913e4bf945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prediction', 'subscription_type_Streaming_pred')
    op.drop_column('prediction', 'subscription_type_TV_and_Streaming_pred')
    op.drop_column('prediction', 'contracted_pred')
    op.drop_column('prediction', 'subscription_type_TV_pred')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction', sa.Column('subscription_type_TV_pred', sa.BOOLEAN(), nullable=True))
    op.add_column('prediction', sa.Column('contracted_pred', sa.INTEGER(), nullable=True))
    op.add_column('prediction', sa.Column('subscription_type_TV_and_Streaming_pred', sa.BOOLEAN(), nullable=True))
    op.add_column('prediction', sa.Column('subscription_type_Streaming_pred', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
