"""Init

Revision ID: 598487da0100
Revises: 
Create Date: 2024-07-08 19:37:43.232781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '598487da0100'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction',
    sa.Column('id_pred', sa.Integer(), nullable=False),
    sa.Column('is_tv_subscriber_pred', sa.Boolean(), nullable=True),
    sa.Column('is_movie_package_subscriber_pred', sa.Boolean(), nullable=True),
    sa.Column('subscription_age_pred', sa.Float(), nullable=True),
    sa.Column('bill_avg_pred', sa.Integer(), nullable=True),
    sa.Column('reamining_contract_pred', sa.Float(), nullable=True),
    sa.Column('contracted_pred', sa.Integer(), nullable=True),
    sa.Column('service_failure_count_pred', sa.Integer(), nullable=True),
    sa.Column('download_avg_pred', sa.Float(), nullable=True),
    sa.Column('upload_avg_pred', sa.Float(), nullable=True),
    sa.Column('download_over_limit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_pred')
    )
    op.create_index(op.f('ix_prediction_id_pred'), 'prediction', ['id_pred'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_id_pred'), table_name='prediction')
    op.drop_table('prediction')
    # ### end Alembic commands ###
