"""subscription_type_Streaming_pred, subscription_type_TV_pred, subscription_type_TV_and_Streaming_pred

Revision ID: 83913e4bf945
Revises: 1c6f74052243
Create Date: 2024-07-13 15:52:45.138904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83913e4bf945'
down_revision: Union[str, None] = '1c6f74052243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction', sa.Column('subscription_type_Streaming_pred', sa.Boolean(), nullable=True))
    op.add_column('prediction', sa.Column('subscription_type_TV_pred', sa.Boolean(), nullable=True))
    op.add_column('prediction', sa.Column('subscription_type_TV_and_Streaming_pred', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prediction', 'subscription_type_TV_and_Streaming_pred')
    op.drop_column('prediction', 'subscription_type_TV_pred')
    op.drop_column('prediction', 'subscription_type_Streaming_pred')
    # ### end Alembic commands ###
